# Solved Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [71]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [72]:
print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lipik/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/lipik/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lipik/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/lipik/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lipik/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/lipik/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/lipik/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/lipik/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10

In [73]:
vec=np.zeros((10),dtype=int)
print(vec)

[0 0 0 0 0 0 0 0 0 0]


#### 4.  How to find the memory size of any array

In [74]:
x=np.array([100,20,34])
print("Memory size of array (in bytes):",x.size * x.itemsize)

Memory size of array (in bytes): 12


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [75]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [76]:
vec2=np.zeros((10),dtype=int)
vec2[4]=1
print(vec2)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49

In [77]:
vec3 = np.arange(10,50)
print(vec3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [78]:
vec3=vec3[::-1]
print(vec3)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [79]:
import numpy as np
matrix=np.arange(0, 9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [80]:
nums = np.array([1,2,0,0,4,0])
result = np.where(nums == 0)[0]
print("Indices: ",result)

Indices:  [2 3 5]


#### 11. Create a 3x3 identity matrix

In [81]:
matrix2=np.identity((3),dtype=int)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 12. Create a 3x3x3 array with random values

In [82]:
arr2=np.random.random((3,3,3))
print(arr2)

[[[0.00840631 0.7016212  0.02568328]
  [0.55514896 0.61450355 0.18259256]
  [0.40530733 0.40530209 0.21216984]]

 [[0.55465366 0.39249343 0.62174331]
  [0.68869566 0.45159396 0.28741232]
  [0.4343092  0.11420706 0.16001392]]

 [[0.50979521 0.1652749  0.62625042]
  [0.04741555 0.9011103  0.1787943 ]
  [0.65447381 0.22832171 0.57979437]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [83]:
arr3=np.random.random((10,10))
print(arr3) 
low,high=arr3.min(),arr3.max()
print()
print("Minimum value: ",low,"\nMaximum value: ",high)

[[0.83205303 0.10363515 0.70691986 0.95267084 0.32029309 0.57374112
  0.60200213 0.56416337 0.16451637 0.08630565]
 [0.99938516 0.41661169 0.87493188 0.15064623 0.42844907 0.73142242
  0.37707357 0.68918218 0.56621821 0.77292235]
 [0.10010303 0.99800814 0.00644792 0.62532842 0.63424073 0.3497547
  0.5210389  0.96580957 0.9000682  0.69251643]
 [0.45457385 0.9035089  0.95725926 0.94608421 0.35698289 0.42365241
  0.65729836 0.50394108 0.47466132 0.17481275]
 [0.92537767 0.33509812 0.27419363 0.85994357 0.949256   0.8645468
  0.67536977 0.84164129 0.97629801 0.56391648]
 [0.05586603 0.00395917 0.77575341 0.25190688 0.13911207 0.44777452
  0.00691204 0.97754555 0.93125068 0.74025763]
 [0.84755809 0.59111657 0.07606281 0.8675006  0.27961535 0.71769032
  0.48398718 0.69045032 0.13595067 0.3546064 ]
 [0.01807644 0.06064699 0.98089356 0.95012527 0.23483641 0.0373928
  0.13867506 0.45566908 0.52248909 0.94039207]
 [0.049747   0.31702141 0.59586893 0.00405752 0.67749736 0.65573988
  0.34390542 0.

#### 14. Create a random vector of size 30 and find the mean value

In [84]:
vec4=np.random.random(30)
print(vec4)
print()
print("Mean value: ",np.mean(vec4))

[0.39987562 0.15144165 0.74426133 0.07109673 0.44875152 0.22197597
 0.57861682 0.32497443 0.14866579 0.49112556 0.18317233 0.06098772
 0.8013392  0.90647692 0.51846648 0.34905672 0.17926065 0.28246183
 0.53385363 0.0722523  0.70753039 0.73496726 0.08763054 0.20438571
 0.8171811  0.77414724 0.8574739  0.23637925 0.8673359  0.75969057]

Mean value:  0.4504945006864921



#### 15. Create a 2d array with 1 on the border and 0 inside

In [85]:
matrix3=np.ones((3,3),dtype=int)
matrix3[1:-1,1:-1] = 0
print(matrix3)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [86]:
matrix3=np.pad(matrix3, pad_width=1, mode='constant', constant_values=0)
print(matrix3)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [87]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [88]:
matrix4=np.diag([1,2,3,4],-1)
print(matrix4)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [89]:
x = np.ones((8,8),dtype=int)
x[1::2,::2] = 0
x[::2,1::2] = 0
print(x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [90]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)
